# fast_hashtable.pyi - Type hints for Cython Hash Table

from typing import Any

class CHashTable:
    def __init__(self, size: int = 8) -> None: ...
    def insert(self, key: str, value: Any) -> None: ...
    def get(self, key: str) -> Any: ...
    def remove(self, key: str) -> None: ...
